# Here are the main program files
from .user_agents import *
from .pretty_print import *
from .availability_checker import *
from .site_data import *
from .proxy_scraper import *
from .config_manager import *
from .logger import *
from .auto_update import *
from .preset_manager import *

# Here are all modules for the sites that are supported
from .anontransfer import *
from .anonymfile import *
from .bowfile import *
from .buzzheavier import *
from .catbox import *
from .clicknupload import *
from .cyberfile import *
from .delafil import *
from .doodrive import *
from .downloadgg import *
from .easyupload import *
from .fastupload import *
from .filebin import *
from .fileio import *
from .filesadmin import *
from .filesfm import *
from .filesi import *
from .files_dp_ua import *
from .fileupload import *
from .gofile import *
from .hexupload import *
from .keep import *
from .krakenfiles import *
from .litterbox import *
from .mixdrop import *
from .onecloudfile import *
from .onefichier import *
from .oshi import *
from .pixeldrain import *
from .rapidgator import *
from .tempsend import *
from .tmpfiles import *
from .transfer import *
from .ufile import *
from .usercloud import *
from .usersdrive import *
from .wdho import *
